// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFBfw6ia5rTmQiEnmjnd1HBPNTviFAeA',
    appId: '1:462836365540:web:12a81306e846e662c2d4f1',
    messagingSenderId: '462836365540',
    projectId: 'gtd-bible-verses-simple-demo',
    authDomain: 'gtd-bible-verses-simple-demo.firebaseapp.com',
    storageBucket: 'gtd-bible-verses-simple-demo.firebasestorage.app',
    measurementId: 'G-H1FWJBZNCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOnh6qOzrFYHm7pU2idz3iGkT-20O-bBI',
    appId: '1:462836365540:android:1313db68759611f2c2d4f1',
    messagingSenderId: '462836365540',
    projectId: 'gtd-bible-verses-simple-demo',
    storageBucket: 'gtd-bible-verses-simple-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF4nWyYBOD1UUBDUa22zL1JBk4fiqs1AQ',
    appId: '1:462836365540:ios:75d624b5ec76fe95c2d4f1',
    messagingSenderId: '462836365540',
    projectId: 'gtd-bible-verses-simple-demo',
    storageBucket: 'gtd-bible-verses-simple-demo.firebasestorage.app',
    iosBundleId: 'com.example.simpleDemo',
  );
}
